import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/ui/Navbar";
import Footer from "./components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zenn Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white dark:bg-bgDark text-gray-900 dark:text-white">
        <Navbar/>
        <div className="mx-auto max-w-2xl px-6 min-h-screen  bg-white dark:bg-bgDark">
        {children}
        </div>
        <Footer/>
        </div>
        </body>
    </html>
  );
}
